version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    # volumes:
    #   - "./data/db:/data/db"
    # ports:
    #   - 27017:27017
  job-application-tracker:
    build: .
    container_name: "job-application-tracker"
    command: yarn dev
    volumes:
      - ./:/server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
